export const FETCH_VOTES = 'FETCH_VOTES';
export const FETCH_VOTES_SUCCESS = 'FETCH_VOTES_SUCCESS';
export const FETCH_VOTES_FAILED = 'FETCH_VOTES_FAILED';

export const FETCH_VOTES_BY_REGION = 'FETCH_VOTES_BY_REGION';
export const FETCH_VOTES_BY_REGION_SUCCESS = 'FETCH_VOTES_BY_REGION_SUCCESS';
export const FETCH_VOTES_BY_REGION_FAILED = 'FETCH_VOTES_BY_REGION_FAILED';

export const FETCH_REGIONS = 'FETCH_REGIONS';
export const FETCH_REGIONS_SUCCESS = 'FETCH_REGIONS_SUCCESS';
export const FETCH_REGIONS_FAILED = 'FETCH_REGIONS_FAILED';

export const FETCH_CANDIDATES = 'FETCH_CANDIDATES';
export const FETCH_CANDIDATES_SUCCESS = 'FETCH_CANDIDATES_SUCCESS';
export const FETCH_CANDIDATES_FAILED = 'FETCH_CANDIDATES_FAILED';

export const CREATE_CANDIDATE = 'CREATE_CANDIDATE';
export const CREATE_CANDIDATE_SUCCESS = 'CREATE_CANDIDATE_SUCCESS';
export const CREATE_CANDIDATE_FAILED = 'CREATE_CANDIDATE_FAILED';

export const UPDATE_CANDIDATE = 'UPDATE_CANDIDATE';
export const UPDATE_CANDIDATE_SUCCESS = 'UPDATE_CANDIDATE_SUCCESS';
export const UPDATE_CANDIDATE_FAILED = 'UPDATE_CANDIDATE_FAILED';

export const DELETE_CANDIDATE = 'DELETE_CANDIDATE';
export const DELETE_CANDIDATE_SUCCESS = 'DELETE_CANDIDATE_SUCCESS';
export const DELETE_CANDIDATE_FAILED = 'DELETE_CANDIDATE_FAILED';

export const DELETE_REGION = 'DELETE_REGION';
export const DELETE_REGION_SUCCESS = 'DELETE_REGION_SUCCESS';
export const DELETE_REGION_FAILED = 'DELETE_REGION_FAILED';

export const CREATE_REGION = 'CREATE_REGION';
export const CREATE_REGION_SUCCESS = 'CREATE_REGION_SUCCESS';
export const CREATE_REGION_FAILED = 'CREATE_REGION_FAILED';

export const UPDATE_REGION = 'UPDATE_REGION';
export const UPDATE_REGION_SUCCESS = 'UPDATE_REGION_SUCCESS';
export const UPDATE_REGION_FAILED = 'UPDATE_REGION_FAILED';

export const FETCH_TOTAL_USERS = 'FETCH_TOTAL_USERS';
export const FETCH_TOTAL_USERS_SUCCESS = 'FETCH_TOTAL_USERS_SUCCESS';
export const FETCH_TOTAL_USERS_FAILED = 'FETCH_TOTAL_USERS_FAILED';

export const UPDATE_VOTES = 'UPDATE_VOTES';

export const CREATE_VOTE = 'CREATE_VOTE';
export const CREATE_VOTE_SUCCESS = 'CREATE_VOTE_SUCCESS';
export const CREATE_VOTE_FAILED = 'CREATE_VOTE_FAILED';

export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';

export const FETCH_VOTE_BY_USER_ID = 'FETCH_VOTE_BY_USER_ID';
export const FETCH_VOTE_BY_USER_ID_SUCCESS = 'FETCH_VOTE_BY_USER_ID_SUCCESS';
export const FETCH_VOTE_BY_USER_ID_FAILED = 'FETCH_VOTE_BY_USER_ID_FAILED';
