export const FETCH_VOTES = 'FETCH_VOTES';
export const FETCH_VOTES_SUCCESS = 'FETCH_VOTES_SUCCESS';
export const FETCH_VOTES_FAILED = 'FETCH_VOTES_FAILED';

export const FETCH_VOTES_BY_REGION = 'FETCH_VOTES_BY_REGION';
export const FETCH_VOTES_BY_REGION_SUCCESS = 'FETCH_VOTES_BY_REGION_SUCCESS';
export const FETCH_VOTES_BY_REGION_FAILED = 'FETCH_VOTES_BY_REGION_FAILED';

export const FETCH_REGIONS = 'FETCH_REGIONS';
export const FETCH_REGIONS_SUCCESS = 'FETCH_REGIONS_SUCCESS';
export const FETCH_REGIONS_FAILED = 'FETCH_REGIONS_FAILED';

export const FETCH_CANDIDATES = 'FETCH_CANDIDATES';
export const FETCH_CANDIDATES_SUCCESS = 'FETCH_CANDIDATES_SUCCESS';
export const FETCH_CANDIDATES_FAILED = 'FETCH_CANDIDATES_FAILED';

export const FETCH_TOTAL_USERS = 'FETCH_TOTAL_USERS';
export const FETCH_TOTAL_USERS_SUCCESS = 'FETCH_TOTAL_USERS_SUCCESS';
export const FETCH_TOTAL_USERS_FAILED = 'FETCH_TOTAL_USERS_FAILED';
